spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres_db:5432/postgres_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER:kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_SERVER:kafka:9092}
  liquibase:
    enabled: true
    database-change-log-lock-table: DATABASECANGELOGLOCKUSERS
    database-change-log-table: DATABASECHANGELOGUSERS
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}